# This is a basic workflow to help you get started with Actions

name: Release Binary

on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
        - windows-latest
        - ubuntu-latest
        - macos-latest
        game:
        - ft
        - dott

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.9
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - run: |
        poetry install -E cutscenes
        if [ "$RUNNER_OS" == "Windows" ]; then
          poetry run build.${{ matrix.game }}.bat
        else
          poetry run bash ./build.${{ matrix.game }}.sh
        fi
      shell: bash
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/remonster --help
    - run: cp LICENSE ./dist/LICENSE
      shell: bash

    - id: string
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ matrix.game }}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.string.outputs.uppercase }}_reMONSTERed-${{ runner.os }}
        path: dist/*
